        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 19 09:52:21 2015
        MODULE QBERT__genmod
          INTERFACE 
            SUBROUTINE QBERT(QUBE,NLINES1,NLINES2,ENERGY_ARRAY,         &
     &SPECIES_FILE,REACTIONS_FILE,SPECIESLIST,I_NUM,ANIONS)
              INTEGER(KIND=4), INTENT(IN) :: I_NUM
              INTEGER(KIND=2), INTENT(IN) :: NLINES2
              INTEGER(KIND=2), INTENT(IN) :: NLINES1
              INTEGER(KIND=2), INTENT(OUT) :: QUBE(NLINES1,NLINES1,1:3)
              REAL(KIND=4), INTENT(OUT) :: ENERGY_ARRAY(NLINES1,3)
              CHARACTER(LEN=80), INTENT(IN) :: SPECIES_FILE
              CHARACTER(LEN=80), INTENT(IN) :: REACTIONS_FILE
              CHARACTER(*), INTENT(OUT) :: SPECIESLIST(NLINES1)
              INTEGER(KIND=4), INTENT(INOUT) :: ANIONS(I_NUM)
            END SUBROUTINE QBERT
          END INTERFACE 
        END MODULE QBERT__genmod
