        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 19 09:52:21 2015
        MODULE SORT_ENERGIES__genmod
          INTERFACE 
            SUBROUTINE SORT_ENERGIES(PRODS,A_EN,B_EN,C_EN)
              INTEGER(KIND=2), INTENT(INOUT) :: PRODS(3)
              REAL(KIND=4), INTENT(IN) :: A_EN
              REAL(KIND=4), INTENT(IN) :: B_EN
              REAL(KIND=4), INTENT(IN) :: C_EN
            END SUBROUTINE SORT_ENERGIES
          END INTERFACE 
        END MODULE SORT_ENERGIES__genmod
